# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioPlayerRev1(grid).ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.albumArtLabel = QtWidgets.QLabel(self.centralwidget)
        self.albumArtLabel.setText("")
        self.albumArtLabel.setObjectName("albumArtLabel")
        self.gridLayout_2.addWidget(self.albumArtLabel, 6, 0, 2, 1)
        self.searchInput = QtWidgets.QLineEdit(self.centralwidget)
        self.searchInput.setMinimumSize(QtCore.QSize(400, 0))
        self.searchInput.setMaximumSize(QtCore.QSize(400, 16777215))
        self.searchInput.setObjectName("searchInput")
        self.gridLayout_2.addWidget(self.searchInput, 0, 2, 1, 1)
        self.trackPositionSlider = QtWidgets.QSlider(self.centralwidget)
        self.trackPositionSlider.setMinimumSize(QtCore.QSize(1111, 91))
        self.trackPositionSlider.setMaximumSize(QtCore.QSize(1111, 91))
        self.trackPositionSlider.setAutoFillBackground(False)
        self.trackPositionSlider.setMaximum(1000)
        self.trackPositionSlider.setSingleStep(1)
        self.trackPositionSlider.setPageStep(2)
        self.trackPositionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trackPositionSlider.setObjectName("trackPositionSlider")
        self.gridLayout_2.addWidget(self.trackPositionSlider, 7, 1, 1, 3)
        self.filterOn = QtWidgets.QCheckBox(self.centralwidget)
        self.filterOn.setObjectName("filterOn")
        self.gridLayout_2.addWidget(self.filterOn, 0, 3, 1, 1)
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.searchLabel.setMaximumSize(QtCore.QSize(40, 20))
        self.searchLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchLabel.setObjectName("searchLabel")
        self.gridLayout_2.addWidget(self.searchLabel, 0, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(191, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(191, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.gridLayout_2.addWidget(self.treeWidget, 5, 0, 1, 1)
        self.collectionTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionTable.sizePolicy().hasHeightForWidth())
        self.collectionTable.setSizePolicy(sizePolicy)
        self.collectionTable.setSizeIncrement(QtCore.QSize(0, 0))
        self.collectionTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.collectionTable.setDragEnabled(False)
        self.collectionTable.setDragDropOverwriteMode(False)
        self.collectionTable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.collectionTable.setObjectName("collectionTable")
        self.collectionTable.setColumnCount(14)
        self.collectionTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.collectionTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.collectionTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.collectionTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.collectionTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.collectionTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.collectionTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.collectionTable.setHorizontalHeaderItem(13, item)
        self.gridLayout_2.addWidget(self.collectionTable, 5, 1, 1, 3)
        self.audioControlsFrame = QtWidgets.QFrame(self.centralwidget)
        self.audioControlsFrame.setMinimumSize(QtCore.QSize(931, 43))
        self.audioControlsFrame.setMaximumSize(QtCore.QSize(931, 43))
        self.audioControlsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audioControlsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audioControlsFrame.setObjectName("audioControlsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.audioControlsFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backButton = QtWidgets.QPushButton(self.audioControlsFrame)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.stopButton = QtWidgets.QPushButton(self.audioControlsFrame)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.playButton = QtWidgets.QPushButton(self.audioControlsFrame)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.pauseButton = QtWidgets.QPushButton(self.audioControlsFrame)
        self.pauseButton.setCheckable(True)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.skipButton = QtWidgets.QPushButton(self.audioControlsFrame)
        self.skipButton.setObjectName("skipButton")
        self.horizontalLayout.addWidget(self.skipButton)
        self.muteButton = QtWidgets.QPushButton(self.audioControlsFrame)
        self.muteButton.setCheckable(True)
        self.muteButton.setObjectName("muteButton")
        self.horizontalLayout.addWidget(self.muteButton)
        self.volumeSlider = QtWidgets.QSlider(self.audioControlsFrame)
        self.volumeSlider.setProperty("value", 70)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout.addWidget(self.volumeSlider)
        self.gridLayout_2.addWidget(self.audioControlsFrame, 9, 1, 1, 3)
        self.filterBox = QtWidgets.QGroupBox(self.centralwidget)
        self.filterBox.setMinimumSize(QtCore.QSize(1111, 105))
        self.filterBox.setMaximumSize(QtCore.QSize(1111, 105))
        self.filterBox.setObjectName("filterBox")
        self.artistLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.artistLabelFilter.setGeometry(QtCore.QRect(10, 23, 30, 16))
        self.artistLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.artistLabelFilter.setObjectName("artistLabelFilter")
        self.artistInputFilter = QtWidgets.QLineEdit(self.filterBox)
        self.artistInputFilter.setGeometry(QtCore.QRect(46, 23, 313, 20))
        self.artistInputFilter.setObjectName("artistInputFilter")
        self.trackLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.trackLabelFilter.setGeometry(QtCore.QRect(365, 23, 53, 16))
        self.trackLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trackLabelFilter.setObjectName("trackLabelFilter")
        self.genreInputFilter = QtWidgets.QLineEdit(self.filterBox)
        self.genreInputFilter.setGeometry(QtCore.QRect(830, 23, 271, 20))
        self.genreInputFilter.setObjectName("genreInputFilter")
        self.genreLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.genreLabelFilter.setGeometry(QtCore.QRect(744, 23, 78, 16))
        self.genreLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.genreLabelFilter.setObjectName("genreLabelFilter")
        self.albumNameInputFilter = QtWidgets.QLineEdit(self.filterBox)
        self.albumNameInputFilter.setGeometry(QtCore.QRect(424, 23, 313, 20))
        self.albumNameInputFilter.setObjectName("albumNameInputFilter")
        self.yearLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.yearLabelFilter.setGeometry(QtCore.QRect(10, 49, 26, 16))
        self.yearLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yearLabelFilter.setObjectName("yearLabelFilter")
        self.yearInputFilter = QtWidgets.QLineEdit(self.filterBox)
        self.yearInputFilter.setGeometry(QtCore.QRect(46, 49, 133, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearInputFilter.sizePolicy().hasHeightForWidth())
        self.yearInputFilter.setSizePolicy(sizePolicy)
        self.yearInputFilter.setObjectName("yearInputFilter")
        self.keyLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.keyLabelFilter.setGeometry(QtCore.QRect(365, 49, 53, 16))
        self.keyLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyLabelFilter.setObjectName("keyLabelFilter")
        self.keyComboFilter = QtWidgets.QComboBox(self.filterBox)
        self.keyComboFilter.setGeometry(QtCore.QRect(424, 50, 120, 20))
        self.keyComboFilter.setObjectName("keyComboFilter")
        self.bpmLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.bpmLabelFilter.setGeometry(QtCore.QRect(10, 75, 24, 16))
        self.bpmLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpmLabelFilter.setObjectName("bpmLabelFilter")
        self.bpmInputFilter = QtWidgets.QLineEdit(self.filterBox)
        self.bpmInputFilter.setGeometry(QtCore.QRect(46, 75, 133, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpmInputFilter.sizePolicy().hasHeightForWidth())
        self.bpmInputFilter.setSizePolicy(sizePolicy)
        self.bpmInputFilter.setObjectName("bpmInputFilter")
        self.energyLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.energyLabelFilter.setGeometry(QtCore.QRect(365, 75, 53, 16))
        self.energyLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.energyLabelFilter.setObjectName("energyLabelFilter")
        self.ratingPlusMinusComboFilter = QtWidgets.QComboBox(self.filterBox)
        self.ratingPlusMinusComboFilter.setGeometry(QtCore.QRect(830, 50, 120, 20))
        self.ratingPlusMinusComboFilter.setObjectName("ratingPlusMinusComboFilter")
        self.mixTypeLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.mixTypeLabelFilter.setGeometry(QtCore.QRect(530, 50, 71, 16))
        self.mixTypeLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mixTypeLabelFilter.setObjectName("mixTypeLabelFilter")
        self.mixTypeComboFilter = QtWidgets.QComboBox(self.filterBox)
        self.mixTypeComboFilter.setGeometry(QtCore.QRect(604, 50, 133, 20))
        self.mixTypeComboFilter.setObjectName("mixTypeComboFilter")
        self.plusMinusLabelFilterYear = QtWidgets.QLabel(self.filterBox)
        self.plusMinusLabelFilterYear.setGeometry(QtCore.QRect(200, 50, 33, 16))
        self.plusMinusLabelFilterYear.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plusMinusLabelFilterYear.setObjectName("plusMinusLabelFilterYear")
        self.yearPlusMinusComboFilter = QtWidgets.QComboBox(self.filterBox)
        self.yearPlusMinusComboFilter.setGeometry(QtCore.QRect(239, 50, 120, 20))
        self.yearPlusMinusComboFilter.setObjectName("yearPlusMinusComboFilter")
        self.bpmPlusMinusComboFilter = QtWidgets.QLabel(self.filterBox)
        self.bpmPlusMinusComboFilter.setGeometry(QtCore.QRect(200, 80, 33, 16))
        self.bpmPlusMinusComboFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpmPlusMinusComboFilter.setObjectName("bpmPlusMinusComboFilter")
        self.bpmPlusMinusComboFilter_2 = QtWidgets.QComboBox(self.filterBox)
        self.bpmPlusMinusComboFilter_2.setGeometry(QtCore.QRect(239, 80, 120, 20))
        self.bpmPlusMinusComboFilter_2.setObjectName("bpmPlusMinusComboFilter_2")
        self.energyComboFilter = QtWidgets.QComboBox(self.filterBox)
        self.energyComboFilter.setGeometry(QtCore.QRect(424, 80, 120, 20))
        self.energyComboFilter.setObjectName("energyComboFilter")
        self.plusMinusLabelFiltertEnergy = QtWidgets.QLabel(self.filterBox)
        self.plusMinusLabelFiltertEnergy.setGeometry(QtCore.QRect(530, 80, 71, 16))
        self.plusMinusLabelFiltertEnergy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plusMinusLabelFiltertEnergy.setObjectName("plusMinusLabelFiltertEnergy")
        self.energyPlusMinusComboFilter = QtWidgets.QComboBox(self.filterBox)
        self.energyPlusMinusComboFilter.setGeometry(QtCore.QRect(604, 80, 120, 20))
        self.energyPlusMinusComboFilter.setObjectName("energyPlusMinusComboFilter")
        self.ratingLabelFilter = QtWidgets.QLabel(self.filterBox)
        self.ratingLabelFilter.setGeometry(QtCore.QRect(752, 50, 71, 20))
        self.ratingLabelFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ratingLabelFilter.setObjectName("ratingLabelFilter")
        self.resetButton = QtWidgets.QPushButton(self.filterBox)
        self.resetButton.setGeometry(QtCore.QRect(830, 80, 120, 23))
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_2.addWidget(self.filterBox, 1, 1, 4, 3)
        self.id3TagBox = QtWidgets.QGroupBox(self.centralwidget)
        self.id3TagBox.setMinimumSize(QtCore.QSize(1111, 105))
        self.id3TagBox.setMaximumSize(QtCore.QSize(1111, 105))
        self.id3TagBox.setObjectName("id3TagBox")
        self.gridLayout = QtWidgets.QGridLayout(self.id3TagBox)
        self.gridLayout.setObjectName("gridLayout")
        self.artistLabel = QtWidgets.QLabel(self.id3TagBox)
        self.artistLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.artistLabel.setObjectName("artistLabel")
        self.gridLayout.addWidget(self.artistLabel, 0, 0, 1, 1)
        self.artistInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.artistInput.setObjectName("artistInput")
        self.gridLayout.addWidget(self.artistInput, 0, 1, 1, 1)
        self.trackLabel = QtWidgets.QLabel(self.id3TagBox)
        self.trackLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trackLabel.setObjectName("trackLabel")
        self.gridLayout.addWidget(self.trackLabel, 0, 2, 1, 1)
        self.trackNameInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.trackNameInput.setObjectName("trackNameInput")
        self.gridLayout.addWidget(self.trackNameInput, 0, 3, 1, 1)
        self.albumLabel = QtWidgets.QLabel(self.id3TagBox)
        self.albumLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.albumLabel.setObjectName("albumLabel")
        self.gridLayout.addWidget(self.albumLabel, 0, 4, 1, 1)
        self.albumNameInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.albumNameInput.setObjectName("albumNameInput")
        self.gridLayout.addWidget(self.albumNameInput, 0, 5, 1, 1)
        self.yearLabel = QtWidgets.QLabel(self.id3TagBox)
        self.yearLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yearLabel.setObjectName("yearLabel")
        self.gridLayout.addWidget(self.yearLabel, 1, 0, 1, 1)
        self.yearInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.yearInput.setObjectName("yearInput")
        self.gridLayout.addWidget(self.yearInput, 1, 1, 1, 1)
        self.remixerLabel = QtWidgets.QLabel(self.id3TagBox)
        self.remixerLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remixerLabel.setObjectName("remixerLabel")
        self.gridLayout.addWidget(self.remixerLabel, 1, 2, 1, 1)
        self.remixerInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.remixerInput.setObjectName("remixerInput")
        self.gridLayout.addWidget(self.remixerInput, 1, 3, 1, 1)
        self.genreLabel = QtWidgets.QLabel(self.id3TagBox)
        self.genreLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.genreLabel.setObjectName("genreLabel")
        self.gridLayout.addWidget(self.genreLabel, 1, 4, 1, 1)
        self.genreCombo = QtWidgets.QComboBox(self.id3TagBox)
        self.genreCombo.setObjectName("genreCombo")
        self.gridLayout.addWidget(self.genreCombo, 1, 5, 1, 1)
        self.bpmLabel = QtWidgets.QLabel(self.id3TagBox)
        self.bpmLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpmLabel.setObjectName("bpmLabel")
        self.gridLayout.addWidget(self.bpmLabel, 2, 0, 1, 1)
        self.bpmInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.bpmInput.setObjectName("bpmInput")
        self.gridLayout.addWidget(self.bpmInput, 2, 1, 1, 1)
        self.keyLabel = QtWidgets.QLabel(self.id3TagBox)
        self.keyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyLabel.setObjectName("keyLabel")
        self.gridLayout.addWidget(self.keyLabel, 2, 2, 1, 1)
        self.keyInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.keyInput.setObjectName("keyInput")
        self.gridLayout.addWidget(self.keyInput, 2, 3, 1, 1)
        self.energyLabel = QtWidgets.QLabel(self.id3TagBox)
        self.energyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.energyLabel.setObjectName("energyLabel")
        self.gridLayout.addWidget(self.energyLabel, 2, 4, 1, 1)
        self.energyInput = QtWidgets.QLineEdit(self.id3TagBox)
        self.energyInput.setObjectName("energyInput")
        self.gridLayout.addWidget(self.energyInput, 2, 5, 1, 1)
        self.gridLayout_2.addWidget(self.id3TagBox, 6, 1, 1, 3)
        self.DeletePlaylist = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeletePlaylist.sizePolicy().hasHeightForWidth())
        self.DeletePlaylist.setSizePolicy(sizePolicy)
        self.DeletePlaylist.setMinimumSize(QtCore.QSize(191, 0))
        self.DeletePlaylist.setMaximumSize(QtCore.QSize(191, 16777215))
        self.DeletePlaylist.setObjectName("DeletePlaylist")
        self.gridLayout_2.addWidget(self.DeletePlaylist, 4, 0, 1, 1)
        self.addPlaylist = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPlaylist.sizePolicy().hasHeightForWidth())
        self.addPlaylist.setSizePolicy(sizePolicy)
        self.addPlaylist.setMinimumSize(QtCore.QSize(191, 0))
        self.addPlaylist.setMaximumSize(QtCore.QSize(191, 16777215))
        self.addPlaylist.setObjectName("addPlaylist")
        self.gridLayout_2.addWidget(self.addPlaylist, 3, 0, 1, 1)
        self.audioControlsFrame.raise_()
        self.id3TagBox.raise_()
        self.collectionTable.raise_()
        self.albumArtLabel.raise_()
        self.treeWidget.raise_()
        self.searchInput.raise_()
        self.searchLabel.raise_()
        self.filterBox.raise_()
        self.filterOn.raise_()
        self.trackPositionSlider.raise_()
        self.DeletePlaylist.raise_()
        self.addPlaylist.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_File = QtWidgets.QAction(MainWindow)
        self.actionAdd_File.setObjectName("actionAdd_File")
        self.actionAdd_Folder = QtWidgets.QAction(MainWindow)
        self.actionAdd_Folder.setObjectName("actionAdd_Folder")
        self.actionSave_Collection = QtWidgets.QAction(MainWindow)
        self.actionSave_Collection.setObjectName("actionSave_Collection")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_Collection = QtWidgets.QAction(MainWindow)
        self.actionLoad_Collection.setObjectName("actionLoad_Collection")
        self.actionSave_Collection_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Collection_As.setObjectName("actionSave_Collection_As")
        self.menuFile.addAction(self.actionAdd_File)
        self.menuFile.addAction(self.actionAdd_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AudioPlayerVer1.0"))
        self.filterOn.setText(_translate("MainWindow", "Filter On/Off"))
        self.searchLabel.setText(_translate("MainWindow", "Search:"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Collection"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Genres"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Playlists"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.collectionTable.setSortingEnabled(True)
        item = self.collectionTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "rowid"))
        item = self.collectionTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Waveform"))
        item = self.collectionTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Track Title"))
        item = self.collectionTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.collectionTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Album"))
        item = self.collectionTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Genre"))
        item = self.collectionTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Key"))
        item = self.collectionTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "BPM"))
        item = self.collectionTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Energy"))
        item = self.collectionTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Rating"))
        item = self.collectionTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Year"))
        item = self.collectionTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Length"))
        item = self.collectionTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Location"))
        item = self.collectionTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Playlists in"))
        self.backButton.setText(_translate("MainWindow", "Back 30 sec"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.skipButton.setText(_translate("MainWindow", "Skip 30 sec"))
        self.muteButton.setText(_translate("MainWindow", "Mute"))
        self.filterBox.setTitle(_translate("MainWindow", "Filter"))
        self.artistLabelFilter.setText(_translate("MainWindow", "Artist:"))
        self.trackLabelFilter.setText(_translate("MainWindow", "Track Title:"))
        self.genreLabelFilter.setText(_translate("MainWindow", "Genre Contains:"))
        self.yearLabelFilter.setText(_translate("MainWindow", "Year:"))
        self.keyLabelFilter.setText(_translate("MainWindow", "Key:"))
        self.bpmLabelFilter.setText(_translate("MainWindow", "BPM:"))
        self.energyLabelFilter.setText(_translate("MainWindow", "Energy:"))
        self.mixTypeLabelFilter.setText(_translate("MainWindow", "Mix Type:"))
        self.plusMinusLabelFilterYear.setText(_translate("MainWindow", "+/- :"))
        self.bpmPlusMinusComboFilter.setText(_translate("MainWindow", "+/- :"))
        self.plusMinusLabelFiltertEnergy.setText(_translate("MainWindow", "+/- :"))
        self.ratingLabelFilter.setText(_translate("MainWindow", "Rating:"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.id3TagBox.setTitle(_translate("MainWindow", "Tags"))
        self.artistLabel.setText(_translate("MainWindow", "Artist:"))
        self.trackLabel.setText(_translate("MainWindow", "Track Title:"))
        self.albumLabel.setText(_translate("MainWindow", "Album:"))
        self.yearLabel.setText(_translate("MainWindow", "Year:"))
        self.remixerLabel.setText(_translate("MainWindow", "Remixer:"))
        self.genreLabel.setText(_translate("MainWindow", "Genre:"))
        self.bpmLabel.setText(_translate("MainWindow", "BPM:"))
        self.keyLabel.setText(_translate("MainWindow", "Key:"))
        self.energyLabel.setText(_translate("MainWindow", "Energy:"))
        self.DeletePlaylist.setText(_translate("MainWindow", "Delete Playlist"))
        self.addPlaylist.setText(_translate("MainWindow", "Add Playlist"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_File.setText(_translate("MainWindow", "Add File"))
        self.actionAdd_Folder.setText(_translate("MainWindow", "Add Folder"))
        self.actionSave_Collection.setText(_translate("MainWindow", "Save Collection"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad_Collection.setText(_translate("MainWindow", "Load Collection"))
        self.actionSave_Collection_As.setText(_translate("MainWindow", "Save Collection As"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
